spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/tax_system_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080